layout_spectrum: 0.4574468
color:
  saturation: 0.8042553
  brandStrength: 0.7294959
  lightness: 0.806383
  rhythmicContrast: 0.7914894
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.3680851
name: Henrik
